services:
  - type: web
    name: tempo-backend
    env: docker
    dockerfilePath: ./BE/Tempo/Dockerfile
    dockerContext: ./BE/Tempo
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5050
